### ISSUE TITLE
Imaginary part it's not computed properly

### ISSUE THREAD

**Issue by Alkesst** [GTFOCrew/gtfo#19]
As you can see in those screenshots, the imaginary part it's not calculated properly. 
![image](https://user-images.githubusercontent.com/20269359/71696221-b444ea80-2db4-11ea-8332-009c2d593e2b.png)
![image](https://user-images.githubusercontent.com/20269359/71696238-be66e900-2db4-11ea-88fd-7d4fe5519ac5.png)

**Comment by Neko250** [comment]
@Alkesst, I suggest using https://www.npmjs.com/package/nerdamer#using-the-solver

**Comment by Alkesst** [comment]
oh fuck
